export {default as Home} from './Home'
export {default as SignUp} from './SignUp'
export {default as Login} from './Login'
export {default as Contact} from './Contact'
export {default as About} from './About'
export {default as Cart } from './Cart'
export {default as Checkout } from './Checkout'
export {default as Whishlist } from './WishList'
export {default as Orders } from './MyOrders'
export {default as Account } from './MyAccount'
